In [2]:
lst = [1,2,3,4]

In [19]:
import numpy as np

# numpy array

        converts list to array 

In [5]:
np.array(lst)

array([1, 2, 3, 4])

In [6]:
mat=[(1,2),(3,4)]

In [20]:
np.array(mat)

array([[1, 2],
       [3, 4]])

# arange
 similar to range in list

In [12]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [21]:
np.zeros(3)

array([0., 0., 0.])

### Create a Matrix with 7X7 zeros with Tupples

In [16]:
np.zeros((7,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [22]:
np.ones(1)

array([1.])

### Create a Matrix with 3X4 one's with Tupples

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# linspace
```
Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.


Examples
--------
>>> np.linspace(2.0, 3.0, num=5)
array([ 2.  ,  2.25,  2.5 ,  2.75,  3.  ])
>>> np.linspace(2.0, 3.0, num=5, endpoint=False)
array([ 2. ,  2.2,  2.4,  2.6,  2.8])
>>> np.linspace(2.0, 3.0, num=5, retstep=True)
(array([ 2.  ,  2.25,  2.5 ,  2.75,  3.  ]), 0.25)

```

In [28]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])