Table of Contents
=================
  
   * [numpy array](#numpy-array)
      * [arange](#arange)
      * [linspace](#linspace)
      * [eye](#eye)
      * [random](#random)
         * [rand](#rand)
         * [randn](#randn)
         * [randint](#randint)
      * [reshape](#reshape)
      * [dtype](#dtype)
   * [numpy_indexing_and_slicing](#numpy_indexing_and_slicing)
      * [indexing](#indexing)
      * [slice](#slice)
      * [slice vs copy](#slice-vs-copy)
      * [2d_array](#2d_array)
         * [conditional Fetching in Arrays](#conditional-fetching-in-arrays)


In [199]:
lst = [1,2,3,4]

In [5]:
import numpy as np

# numpy array

        converts list to array 

In [6]:
np.array(lst)

array([1, 2, 3, 4])

In [7]:
mat=[(1,2),(3,4)]

In [8]:
np.array(mat)

array([[1, 2],
       [3, 4]])

## arange
 similar to range in list

In [9]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [10]:
np.zeros(3)

array([0., 0., 0.])

> Create a Matrix with 7X7 zeros with Tupples

In [11]:
np.zeros((7,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [12]:
np.ones(1)

array([1.])

> Create a Matrix with 3X4 one's with Tupples

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## linspace

```
Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.


Examples
--------
>>> np.linspace(2.0, 3.0, num=5)
array([ 2.  ,  2.25,  2.5 ,  2.75,  3.  ])
>>> np.linspace(2.0, 3.0, num=5, endpoint=False)
array([ 2. ,  2.2,  2.4,  2.6,  2.8])
>>> np.linspace(2.0, 3.0, num=5, retstep=True)
(array([ 2.  ,  2.25,  2.5 ,  2.75,  3.  ]), 0.25)

```



In [14]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [56]:
np.linspace(0,10,35)

array([ 0.        ,  0.29411765,  0.58823529,  0.88235294,  1.17647059,
        1.47058824,  1.76470588,  2.05882353,  2.35294118,  2.64705882,
        2.94117647,  3.23529412,  3.52941176,  3.82352941,  4.11764706,
        4.41176471,  4.70588235,  5.        ,  5.29411765,  5.58823529,
        5.88235294,  6.17647059,  6.47058824,  6.76470588,  7.05882353,
        7.35294118,  7.64705882,  7.94117647,  8.23529412,  8.52941176,
        8.82352941,  9.11764706,  9.41176471,  9.70588235, 10.        ])

## eye

In [55]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## random
### rand
    random number between 0 and 1
    
        Docstring:
        rand(d0, d1, ..., dn)

        Random values in a given shape.

In [21]:
np.random.rand()

0.05489564721339513

In [60]:
np.random.rand(5) # single Dimension

array([0.65448174, 0.47742514, 0.09581925, 0.51734036, 0.57321911])

In [61]:
np.random.rand(3,4) # Two Dimension

array([[0.1617407 , 0.5024782 , 0.50960348, 0.19866051],
       [0.53766199, 0.36107611, 0.18214015, 0.0895943 ],
       [0.18772053, 0.30412282, 0.62939018, 0.30317754]])

### randn

        Docstring:
        randn(d0, d1, ..., dn)

        Return a sample (or samples) from the "standard normal" distribution.

In [24]:
np.random.randn()

0.43446717719977324

In [25]:
np.random.randn(3)

array([-0.49468215, -0.60279249, -0.53800381])

In [62]:
np.random.randn(3,3)

array([[ 1.05783442, -0.49681774, -0.27558728],
       [-0.03080465, -0.36565986, -3.2559658 ],
       [ 0.93596735, -0.95393637, -0.87242756]])

### randint 

        Docstring:
        randint(low, high=None, size=None, dtype='l')

        Return random integers from `low` (inclusive) to `high` (exclusive).

In [33]:
np.random.randint(100)

74

In [37]:
np.random.randint(1,100,4)

array([24, 38, 45, 87])

In [38]:
arr = np.arange(25)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [74]:
ranarr = np.random.randint(1,100,25)

In [75]:
ranarr

array([62, 72, 17, 38,  5,  3, 62,  7, 23,  8,  9, 87, 19, 79, 97, 34, 92,
       91,  4, 52, 64, 28, 76, 66, 68])

## reshape

    Docstring:
    a.reshape(shape, order='C')

    Returns an array containing the same data with a new shape.

In [76]:
ranarr.reshape(5,5)

array([[62, 72, 17, 38,  5],
       [ 3, 62,  7, 23,  8],
       [ 9, 87, 19, 79, 97],
       [34, 92, 91,  4, 52],
       [64, 28, 76, 66, 68]])

In [77]:
ranarr.max() # max Value in the arr

97

In [79]:
ranarr.min()  # min Value in the arr

3

In [80]:
ranarr.argmax()     # Index of max Value in the arr

14

In [81]:
ranarr.argmin()     # Index of min Value in the arr

5

In [82]:
ranarr.shape       # Type of Array ,.. single,double ..dimentional

(25,)

In [84]:
ranarr=ranarr.reshape(5,5)

In [101]:
ranarr.shape

(5, 5)

## dtype

```

        Create a data type object.

        A numpy array is homogeneous, and contains elements described by a
        dtype object. A dtype object can be constructed from different
        combinations of fundamental numeric types.

        Parameters
        ----------
        obj
            Object to be converted to a data type object.
        align : bool, optional
            Add padding to the fields to match what a C compiler would output
            for a similar C-struct. Can be ``True`` only if `obj` is a dictionary
            or a comma-separated string. If a struct dtype is being created,
            this also sets a sticky alignment flag ``isalignedstruct``.
        copy : bool, optional
            Make a new copy of the data-type object. If ``False``, the result
            may just be a reference to a built-in data-type object.


        Examples
        --------
        Using array-scalar type:

        >>> np.dtype(np.int16)
        dtype('int16')
        
```

In [90]:
ranarr.dtype        # Data Type of Array,..... int64,

dtype('int64')

In [98]:
s=[1,2,'3']

In [99]:
ss= np.array(s)

In [100]:
ss.dtype

dtype('<U21')

> **Simple way to import numpy methods**

In [102]:
from numpy.random import randint

In [103]:
randint(3,10,4)

array([8, 7, 5, 6])

# numpy_indexing_and_slicing

## indexing

In [117]:
lst=[0,1,2,3,4,5,6,7,8,9,10]

In [118]:
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [119]:
lst[0]

0

In [106]:
import numpy as np

In [112]:
npArr=np.arange(10)

In [113]:
npArr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
npArr[0]

0

In [120]:
npArr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
npArr[0:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
npArr[:5]

array([0, 1, 2, 3, 4])

In [123]:
npArr[0:5]

array([0, 1, 2, 3, 4])

In [124]:
npArr[5:]

array([5, 6, 7, 8, 9])

In [125]:
npArr[0:5]=100   # <------ Note : Broadcast the value to range of index

In [126]:
npArr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

## slice

In [130]:
a=np.arange(10,20)

In [131]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [132]:
slice_of_a = a[0:5]

In [135]:
slice_of_a[:]

array([10, 11, 12, 13, 14])

In [136]:
slice_of_a[]=99      # <------ Note : See this FAILS

SyntaxError: invalid syntax (<ipython-input-136-b9e8c308f4f8>, line 1)

In [137]:
slice_of_a[:]=99  # <------ Note : See this PASS "[:]"

In [138]:
slice_of_a

array([99, 99, 99, 99, 99])

Well Now CheckOut this 

In [139]:
a

array([99, 99, 99, 99, 99, 15, 16, 17, 18, 19])

Strange Is'nt It.....We Just Changed slice_of_a but why a also changed it Values ???

**NumPy actually Makes a View/Reference to Original Source but not copy the source ....so changes made in 'slice_of_a' is actually change made to 'a'**

**Why this?**

----> **In Order to Avoid Memory issues Numpy Does this**


So **How to Copy the Array then ????**

Answer : **array.copy()**

In [178]:
b=np.arange(20,30)

In [179]:
b

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [180]:
bcopy = b.copy()

In [181]:
bcopy

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [182]:
bcopy[0:3]=0

In [183]:
bcopy

array([ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29])

In [184]:
b          # <------ NOTE : original Source not changed...

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

## slice vs copy

In [185]:
b=np.arange(80,90)

In [186]:
b

array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89])

In [187]:
bcopy=b.copy()

In [188]:
bcopy

array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89])

In [189]:
bslice=b[:]

In [190]:
bslice

array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89])

In [191]:
bcopy[0:5]=5

In [192]:
bcopy

array([ 5,  5,  5,  5,  5, 85, 86, 87, 88, 89])

In [193]:
b     # <------- NOTE : Source not Changed

array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89])

In [194]:
bslice[0:5]=5

In [195]:
bslice

array([ 5,  5,  5,  5,  5, 85, 86, 87, 88, 89])

In [196]:
b     # <------- NOTE : Source Changed

array([ 5,  5,  5,  5,  5, 85, 86, 87, 88, 89])

## 2d_array
**Now Lets Move on To Next ---->>>**

In [197]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [198]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


>There are Two General Methods to Access Elements From 2d Array
- a.Double Bracket Format
- b.single Bracjet with Comma

In [200]:
arr_2d[1][2]

6

In [201]:
arr_2d[1,2]     # <------ NOTE : Single bracket Notation

6

> **Accessing Specific Elements in Array/ Sub Sections**

In [202]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [204]:
arr_2d[:2,1:]        # <---- Analyse this Carefully

array([[2, 3],
       [5, 6]])

> Now Select 5,6,8,9

In [205]:
arr_2d[1:,1:]

array([[5, 6],
       [8, 9]])

### conditional fetching in arrays

> We can get check condition against array and get the boolean values...and access the Values of Array Which are true

In [206]:
arr=np.arange(1,11)

In [207]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [208]:
arr>5       #<-------- NOTE : Here comparing the values of arr which are greater than 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [209]:
boolean = arr>5

In [212]:
boolean

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

> So these the values of 'arr' which are satisfy the condition..basically this is kind of **Filtering**

In [211]:
arr[boolean]

array([ 6,  7,  8,  9, 10])

> As Simple as Such Fetch all the Elements of arr which are > 5 , can be fetched as below

In [214]:
arr[arr>5]      # <----- same as arr[boolean]

array([ 6,  7,  8,  9, 10])

In [217]:
arr[arr<7]

array([1, 2, 3, 4, 5, 6])

> **Now Lets Move Ahead**

In [218]:
arr=np.arange(50).reshape(5,10)

In [219]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [221]:
arr[1:3,3:5]

array([[13, 14],
       [23, 24]])

# numpy operations

In [1]:
import numpy as np

In [9]:
arr=np.arange(0,10)

In [10]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

> Notice in unsupported errror array vs python

In [13]:
1/0

ZeroDivisionError: division by zero

In [14]:
arr/arr

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [15]:
1/arr

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [18]:
arr **2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

> **Numpy Universal array Functions**
- [https://docs.scipy.org/doc/numpy/reference/ufuncs.html](https://docs.scipy.org/doc/numpy/reference/ufuncs.html)



In [19]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [20]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [21]:
np.max(arr)

9

___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 10 zeros 

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [22]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [24]:
np.zeros(10)+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [5]:
np.arange(10,40)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

#### Create an array of all the even integers from 10 to 50

In [7]:
np.arange(10,52,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [26]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [14]:
np.random.rand()

0.15337873216454756

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [15]:
np.random.randn(25)

array([ 0.30567929, -0.18862583,  0.71651656, -0.59620555,  1.42464664,
        1.01828911, -1.52369884,  0.43953615, -0.01312377, -1.02756418,
        0.03550004,  1.63810721,  0.11135738,  0.31853599,  1.63483293,
       -2.18835297, -0.01042322, -0.20579548, -0.70463306,  0.04001223,
       -0.38441773,  0.20913193, -2.40333554,  0.5596949 ,  0.79268617])

#### Create the following matrix:

```
array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])
       ```
       
>  **This can be done in Two Ways As Shown Below**

In [35]:
np.linspace(0.01,1.00,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [38]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [39]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [43]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [44]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

#array([[12, 13, 14, 15],
#       [17, 18, 19, 20],
#       [22, 23, 24, 25]])

In [47]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
# 20

In [48]:
mat[3,4]

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
# array([[ 2],
#        [ 7],
#        [12]])

In [56]:
mat[:3,1].reshape(3,1)        # NOTE : SEE THIS

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
# array([21, 22, 23, 24, 25])

In [61]:
mat[4]

array([21, 22, 23, 24, 25])

In [62]:
mat[-1]

array([21, 22, 23, 24, 25])

In [58]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

# array([[16, 17, 18, 19, 20],
#        [21, 22, 23, 24, 25]])

In [59]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [63]:
mat.sum()

325

In [64]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [66]:
np.std(mat)

7.211102550927978

In [67]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [68]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

# Great Job!